### ISSUE TITLE
ЕДТ 2022.*

### ISSUE THREAD

**Issue by Jimmi910** [YanSergey/edt.cf_builder#10]
Будет ли адаптация для новой версии ЕДТ ?

**Comment by YanSergey** [comment]
Да, постараюсь в ближайшее время сделать

**Comment by YanSergey** [comment]
Я все таки сделал это =)
Пробуйте, версия 1.3.4

**Comment by UsVfxArtia** [comment]
Не удается завершить установку, так как не удалось найти один или несколько необходимых элементов.
  Устанавливаемое программное обеспечение: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group 1.3.4.v202210060657)
  Отсутствующее требование: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui 1.3.4.v202210060657) требует 'osgi.bundle; com._1c.g5.v8.dt.metadata [14.0.0,15.0.0)', но его не удалось найти
  Не возможно удовлетворить зависимость:
    Из: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group 1.3.4.v202210060657)
    Что: org.eclipse.equinox.p2.iu; ru.yanygin.dt.cfbuilder.plugin.ui [1.3.4.v202210060657,1.3.4.v202210060657]
    
    
    Это ошибка при установке....

**Comment by YanSergey** [comment]
> это ошибка при установке ....
> 
> Не удается завершить установку, так как не удалось найти один или несколько необходимых элементов. Устанавливаемое программное обеспечение: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group 1.3.4.v202210060657) Отсутствующее требование: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui 1.3.4.v202210060657) требует 'osgi.bundle; com._1c.g5.v8.dt.metadata [14.0.0,15.0.0)', но его не удалось найти Не возможно удовлетворить зависимость: Из: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group 1.3.4.v202210060657) Что: org.eclipse.equinox.p2.iu; ru.yanygin.dt.cfbuilder.plugin.ui [1.3.4.v202210060657,1.3.4.v202210060657]

Вы устанавливаете из файла или с сайта?
Версия EDT 2022.1.2 (финальная сборка) или тестовая сборка (2022.1.0 или 2022.1.1)?

**Comment by Sicyro** [comment]
У меня такая же ошибка оказалась:
Устанавливал из файла(архив)
Версия EDT 2022.1.2 (финальная сборка)

Ошибка вылезла при перезапуске EDT

**Comment by YanSergey** [comment]
Это очень странно.
Наверняка у вас в каталоге plugins нет файла **com._1c.g5.v8.dt.metadata_14.0.0.v202209161208.jar**
![image](https://user-images.githubusercontent.com/24665801/195768100-37131c09-4e3b-4d35-b807-d9a94662f56c.png)
Какой версии файл у вас там лежит? Установка EDT оффлайн или через стартер?

**Comment by Sicyro** [comment]
Установка офлайн версии 
![image](https://user-images.githubusercontent.com/91005913/195807234-b5412365-5b93-4a58-aed5-f1811b23e511.png)

**Comment by YanSergey** [comment]
Видно, что файл нужный есть.
Значит при установке к нему доступ есть, а после перезапуска почему то нет.
Попробуйте скопировать полностью каталог с ЕДТ в другое место, может проблема с правами на "Program Files".

**Comment by Sicyro** [comment]
Добрый день! Извиняюсь что долго отвечал. Всё сработало. В компании при установки запрещался доступ ко всем файлам в папке с EDT. Решилось тем что открыли доступ к файлам под обычным пользователем

**Comment by YanSergey** [comment]
Отлично
