### ISSUE TITLE
2022.2.3

### ISSUE THREAD

**Issue by Jimmo910** [YanSergey/edt.cf_builder#11]
Не удается установить плагин в версию Ruby 2022.2.3

Не удается завершить установку, так как не удалось найти один или несколько необходимых элементов.
  Устанавливаемое программное обеспечение: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group 1.3.4.v202210060657)
  Отсутствующее требование: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui 1.3.4.v202210060657) требует 'osgi.bundle; com._1c.g5.v8.dt.platform [7.0.0,9.0.0)', но его не удалось найти
  Не возможно удовлетворить зависимость:
    Из: 1C:EDT CF builder 1.3.4.v202210060657 (ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group 1.3.4.v202210060657)
    Что: org.eclipse.equinox.p2.iu; ru.yanygin.dt.cfbuilder.plugin.ui [1.3.4.v202210060657,1.3.4.v202210060657]

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/122779512/216527698-37aae7b8-d185-4c26-bf3e-86487f1aa42b.png">

**Comment by YanSergey** [comment]
Понял. Беру в работу

**Comment by YanSergey** [comment]
Пробуйте
https://github.com/YanSergey/edt.cf_builder/releases/tag/1.3.5

**Comment by Jimmo910** [comment]
Все норм. Работает! Спасибо большое!
