### ISSUE TITLE
Ошибка установки на EDT 2023.1.4

### ISSUE THREAD

**Issue by UstinovGit** [YanSergey/edt.cf_builder#16]
Не удается завершить установку, так как не удалось найти один или несколько необходимых элементов.
  Установленное программное обеспечение: 1C:Enterprise Development Tools License Feature 0.19.0.v202307192055 (com._1c.g5.v8.dt.platform.support_v8.3.18.feature.feature.group 0.19.0.v202307192055)
  Отсутствующее требование: 1C:Enterprise Development Tools License Feature 0.19.0.v202307192055 (com._1c.g5.v8.dt.platform.support_v8.3.18.feature.feature.group 0.19.0.v202307192055) требует 'org.eclipse.equinox.p2.iu; com._1c.g5.v8.dt.platform_v8.3.18 [1.0.600.v202307192055,1.0.600.v202307192055]', но его не удалось найти
![Скрин_едт](https://github.com/YanSergey/edt.cf_builder/assets/164115736/12590909-5d29-4471-bf1d-6212cff56873)

**Comment by UstinovGit** [comment]
будет адаптация под 2023 ?

**Comment by YanSergey** [comment]
> будет адаптация под 2023 ?

Две недели назад проверял установку и работу последней версии плагина на EDT 2023.2.4.
Установилась из репозитория и заработала без ошибок.
Странно что на вашей 2023.1.4 не установилась. Попробую проверить.

**Comment by UstinovGit** [comment]
Да, обновил версию - все заработало, спасибо.

**Comment by YanSergey** [comment]
ОК, значит не буду под 2023.1.4 делать

**Comment by UstinovGit** [comment]
![Безымянный4](https://github.com/YanSergey/edt.cf_builder/assets/164115736/0071a295-f0bc-444d-9b92-b639dc992e9f)
Жаль только, что импортировать не хочет.

**Comment by YanSergey** [comment]
В таком случае посмотрю

**Comment by UstinovGit** [comment]
проблема по другому решена, можно не смотреть
