### ISSUE TITLE
При установке что с репозитория, что из ЗИПа выдает ошибку:

### ISSUE THREAD

**Issue by serjevski** [YanSergey/edt.cf_builder#7]
```
Не удается завершить установку, так как не удалось найти один или несколько необходимых элементов.
  Устанавливаемое программное обеспечение: 1C:EDT CF builder 1.3.0.202012242114 (ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group 1.3.0.202012242114)
  Отсутствующее требование: 1C:EDT CF builder 1.3.0.202012242114 (ru.yanygin.dt.cfbuilder.plugin.ui 1.3.0.202012242114) требует 'osgi.bundle; com._1c.g5.v8.dt.platform [7.0.0,8.0.0)', но его не удалось найти
  Не возможно удовлетворить зависимость:
    Из: 1C:EDT CF builder 1.3.0.202012242114 (ru.yanygin.dt.cfbuilder.plugin.ui.feature.feature.group 1.3.0.202012242114)
    Что: org.eclipse.equinox.p2.iu; ru.yanygin.dt.cfbuilder.plugin.ui [1.3.0.202012242114,1.3.0.202012242114]
```

**Comment by YanSergey** [comment]
Версия EDT 2021.1 ?

**Comment by serjevski** [comment]
> 
> 
> Версия EDT 2021.1 ?

да.

**Comment by YanSergey** [comment]
> > Версия EDT 2021.1 ?
> 
> да.

Проблема известна, В ближайшее время исправлю.

**Comment by serjevski** [comment]
> > да.
> 
> Проблема известна, В ближайшее время исправлю.

Спасибо :)

**Comment by YanSergey** [comment]
> > > да.
> > 
> > 
> > Проблема известна, В ближайшее время исправлю.
> 
> Спасибо :)

@serjevski 
В пререлиз выложил версию 1.3.1, потестируйте пожалуйста.

https://github.com/YanSergey/edt.cf_builder/releases/tag/1.3.1

**Comment by serjevski** [comment]
Да, все работает, спасибо. А можно ли в выходной путь/имя выходного файла добавить возиожнось илспользования макрсов, по типу Обновлятора. Он там вставляет название ИБ давту/время экспорта, версию и т.д.

**Comment by YanSergey** [comment]
> А можно ли в выходной путь/имя выходного файла добавить возиожнось илспользования макрсов

Не планировал больше расширять функционал данного плагина.
Вы можете оформить на это отдельное ишью, может быть, если оно наберет много лайков, то займусь =)
