### ISSUE TITLE
EDT 2021.2

### ISSUE THREAD

**Issue by DitriXNew** [YanSergey/edt.cf_builder#9]
Не хочет ставиться на 2021.2
![image](https://user-images.githubusercontent.com/11927866/125840101-dea368b8-353f-4d8d-8c2f-8fa4f30ba05d.png)

**Comment by YanSergey** [comment]
Спасибо за инфу, постараюсь поскорее починить.

**Comment by YanSergey** [comment]
> Не хочет ставиться на 2021.2

Сделал адаптацию плагина под версию EDT 2021.2
https://github.com/YanSergey/edt.cf_builder/releases/tag/1.3.2

**Comment by Mishell777** [comment]
День добрый!
Проект еще жив?
Не ставится на 2021.3.3.4

**Comment by YanSergey** [comment]
> День добрый! Проект еще жив? Не ставится на 2021.3.3.4

Проект не развиваю, только адаптирую под свежие версии EDT.

Вы пробовали версию плагина 1.3.3? Это предварительная версия (пока сама EDT 2021.3 не зарелизилась).
Доступна по ссылке
https://github.com/YanSergey/edt.cf_builder/releases/tag/untagged-c3db648f635517874960

**Comment by Mishell777** [comment]
День добрый!

 

Нет не пробовал – не могу скачать ☹, по ссылке в браузере 404, в EDT – Сайт с программным обеспечением не наден

**Comment by Mishell777** [comment]
Not Found

**Comment by YanSergey** [comment]
> Not Found

Только что сам проверил - файл скачивается. Попробуйте другой браузер.

**Comment by Mishell777** [comment]
Спасибо! Сегодня в EDT прошло!!! Ура!
